[package]
name = "creole-rs"
version = "0.1.0"
authors = ["carnoxen <carnoxen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
=======
pest = "2.0"
pest_derive = "2.0"
>>>>>>> 7a85d6884d655080ee4cb38392362c63093ff860
